CREATE TABLE public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  author_address text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT comments_pkey PRIMARY KEY (id)
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public comments are viewable by everyone." ON public.comments
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own comments." ON public.comments
  FOR INSERT WITH CHECK (true);
