CREATE TABLE public.purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  buyer_address text NOT NULL,
  tx_hash text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS and allow everyone to read, but only insert their own purchases
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public purchases are viewable by everyone." ON public.purchases
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own purchases." ON public.purchases
  FOR INSERT WITH CHECK (true); 