CREATE TABLE public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  price numeric DEFAULT 0,
  author_address text NOT NULL
);